apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: shoe-recommender
data:
  EMBEDDING_MODEL_ID: "text-embedding-3-small"
  LLM_MODEL_ID: "gpt-4o-mini"
  CORS_ALLOW_ORIGINS: '["https://shoes.isaacpressman.com"]'