apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: shoe-recommender
data:
  config.yaml: |
    tunnel: c5da395e-3f61-4fa5-850a-acbbc8535e1b
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: shoes.isaacpressman.com
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - service: http_status:404